version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rcr-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - mongodb
    networks:
      - rcr_network

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ${MONGO_PATH}:/data/db
    ports:
      - ${MONGO_PORTS}:27017
    networks:
      - rcr_network

networks:
  rcr_network:
    driver: bridge
